// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_frontend-fixes-plan.md.
import { Component, type ErrorInfo, type ReactNode } from 'react';

interface ErrorBoundaryProps {
  children: ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, info: ErrorInfo) {
    console.error('Unhandled render error:', error, info.componentStack);
  }

  handleReload = () => {
    window.location.reload();
  };

  render() {
    if (this.state.hasError) {
      return (
        <div className="flex min-h-screen items-center justify-center bg-bg-1 px-6 text-text">
          <div className="max-w-md space-y-4 border border-border bg-bg-2 p-6 shadow-[0_20px_80px_rgba(0,0,0,0.3)]">
            <p className="text-xs uppercase tracking-[0.24em] text-text-faint">Application error</p>
            <h1 className="text-xl font-semibold text-text">
              Something went wrong.
            </h1>
            <p className="text-sm text-text-muted">
              An unexpected error occurred while rendering this page.
            </p>
            {this.state.error ? (
              <pre className="overflow-x-auto border border-border bg-bg-3 p-3 text-xs leading-5 text-red">
                {this.state.error.message}
              </pre>
            ) : null}
            <button
              type="button"
              onClick={this.handleReload}
              className="border border-border-strong bg-bg-3 px-4 py-2 text-sm text-text transition-colors hover:bg-bg-4"
            >
              Reload
            </button>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}
