// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_m2-flows-workbench.md.
import { formatJson } from '@/lib/utils';
import { nodeStatusClasses } from '@/lib/status-styles';
import type { FlowNode, NodeState, NodeStateStatus } from '@/types/taskr';

interface NodeTreeProps {
  nodes: FlowNode[];
  /** Per-node run status. When provided, a status badge is rendered per node. */
  nodeStatusMap?: Map<string, NodeStateStatus>;
  /** Alternative to nodeStatusMap: raw node states from which per-node status is derived. */
  nodeStates?: NodeState[];
  /** When provided, clicking a node's title calls this with the node id. */
  onSelectNode?: (nodeId: string) => void;
  /** Node id of the currently selected node (for highlight). */
  selectedNodeId?: string | null;
}

function deriveNodeStatusMap(states: NodeState[] | undefined): Map<string, NodeStateStatus> {
  if (!states || states.length === 0) {
    return new Map();
  }
  const grouped = new Map<string, NodeState[]>();
  for (const state of states) {
    const existing = grouped.get(state.node_id) ?? [];
    existing.push(state);
    grouped.set(state.node_id, existing);
  }
  const result = new Map<string, NodeStateStatus>();
  for (const [nodeId, nodeStates] of grouped) {
    if (nodeStates.some((s) => s.status === 'failed')) {
      result.set(nodeId, 'failed');
    } else if (nodeStates.some((s) => s.status === 'running')) {
      result.set(nodeId, 'running');
    } else if (nodeStates.some((s) => s.status === 'dispatching')) {
      result.set(nodeId, 'dispatching');
    } else if (nodeStates.some((s) => s.status === 'ready')) {
      result.set(nodeId, 'ready');
    } else if (nodeStates.some((s) => s.status === 'cancelled')) {
      result.set(nodeId, 'cancelled');
    } else if (nodeStates.length > 0 && nodeStates.every((s) => s.status === 'completed')) {
      result.set(nodeId, 'completed');
    } else {
      result.set(nodeId, 'pending');
    }
  }
  return result;
}

function JsonBlock({ label, value }: { label: string; value: unknown }) {
  if (!value) {
    return null;
  }

  return (
    <div className="space-y-2 border border-white/10 bg-black/10 p-3">
      <p className="text-xs uppercase tracking-[0.24em] text-[#7fa19b]">{label}</p>
      <pre className="overflow-x-auto whitespace-pre-wrap break-words text-xs text-[#e8f1ef]">{formatJson(value)}</pre>
    </div>
  );
}

function StatusBadge({ status }: { status: NodeStateStatus }) {
  return (
    <span className={`inline-flex px-2 py-1 text-xs font-medium uppercase tracking-[0.15em] ring-1 ${nodeStatusClasses[status]}`}>
      {status}
    </span>
  );
}

function NodeCard({
  node,
  depth,
  statusMap,
  onSelectNode,
  selectedNodeId,
}: {
  node: FlowNode;
  depth: number;
  statusMap: Map<string, NodeStateStatus>;
  onSelectNode?: (nodeId: string) => void;
  selectedNodeId?: string | null;
}) {
  const hasChildren = node.children.length > 0;
  const status = statusMap.get(node.id);
  const isSelected = selectedNodeId === node.id;

  return (
    <li>
      <details
        className={[
          'border bg-[#08262b]',
          isSelected ? 'border-accent/60 bg-accent/5' : 'border-white/10',
        ].join(' ')}
        open={depth < 2 || !hasChildren}
      >
        <summary className="cursor-pointer list-none px-4 py-3">
          <div className="flex flex-wrap items-center gap-2">
            {onSelectNode ? (
              <button
                className="border border-accent/30 bg-accent/10 px-2 py-0.5 text-xs font-semibold uppercase tracking-[0.15em] text-accent transition-colors hover:bg-accent/20"
                type="button"
                onClick={(event) => {
                  event.preventDefault();
                  event.stopPropagation();
                  onSelectNode(node.id);
                }}
              >
                Inspect
              </button>
            ) : null}
            <span className="border border-[#d7a63f]/40 bg-[#d7a63f]/10 px-2 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-[#ffd98a]">
              {node.kind}
            </span>
            <span className="text-sm text-[#8fa5a0]">#{node.ord}</span>
            <span className="text-base font-semibold text-white">{node.title}</span>
            {status ? <StatusBadge status={status} /> : null}
            {node.binding_id ? (
              <span className="border border-cyan-400/20 bg-cyan-400/10 px-2 py-1 text-xs text-cyan-200">
                binding {node.binding_id}
              </span>
            ) : null}
            {hasChildren ? <span className="text-xs text-[#7fa19b]">{node.children.length} child nodes</span> : null}
          </div>
        </summary>

        <div className="space-y-3 border-t border-white/10 px-4 py-4">
          <div className="grid gap-3 md:grid-cols-2">
            <JsonBlock label="Input mapping" value={node.input_mapping} />
            <JsonBlock label="Output mapping" value={node.output_mapping} />
          </div>

          {node.kind === 'foreach' ? (
            <dl className="grid gap-3 border border-white/10 bg-black/10 p-3 text-sm md:grid-cols-2">
              <div>
                <dt className="text-xs uppercase tracking-[0.24em] text-[#7fa19b]">Items path</dt>
                <dd className="mt-1 text-[#e8f1ef]">{node.items_path ?? '—'}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase tracking-[0.24em] text-[#7fa19b]">Item key path</dt>
                <dd className="mt-1 text-[#e8f1ef]">{node.item_key_path ?? '—'}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase tracking-[0.24em] text-[#7fa19b]">Failure policy</dt>
                <dd className="mt-1 text-[#e8f1ef]">{node.failure_policy ?? '—'}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase tracking-[0.24em] text-[#7fa19b]">Policy refs</dt>
                <dd className="mt-1 text-[#e8f1ef]">{node.policy_refs?.join(', ') || '—'}</dd>
              </div>
            </dl>
          ) : null}

          {hasChildren ? (
            <div>
              <p className="mb-3 text-xs uppercase tracking-[0.24em] text-[#7fa19b]">Children</p>
              <ul className="space-y-3">
                {node.children.map((child) => (
                  <NodeCard
                    key={child.id}
                    depth={depth + 1}
                    node={child}
                    statusMap={statusMap}
                    onSelectNode={onSelectNode}
                    selectedNodeId={selectedNodeId}
                  />
                ))}
              </ul>
            </div>
          ) : null}
        </div>
      </details>
    </li>
  );
}

export function NodeTree({ nodes, nodeStatusMap, nodeStates, onSelectNode, selectedNodeId }: NodeTreeProps) {
  const statusMap = nodeStatusMap ?? deriveNodeStatusMap(nodeStates);

  if (nodes.length === 0) {
    return (
      <div className="border border-dashed border-white/15 bg-white/5 p-6 text-sm text-[#9eb0ad]">
        No nodes exist for this flow version yet.
      </div>
    );
  }

  return (
    <ul className="space-y-4">
      {nodes.map((node) => (
        <NodeCard
          depth={0}
          key={node.id}
          node={node}
          onSelectNode={onSelectNode}
          selectedNodeId={selectedNodeId}
          statusMap={statusMap}
        />
      ))}
    </ul>
  );
}
