// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /tmp/taskr-budget-frontend-plan.md.
import { useCallback, useEffect, useState } from 'react';

/**
 * Client-side budget settings persisted in localStorage.
 * The backend does not track budget caps yet — these are per-browser preferences.
 */

const CENTS_KEY = 'taskr.budget.cents';
const THRESHOLD_KEY = 'taskr.budget.threshold';
const LABEL_KEY = 'taskr.budget.label';

const DEFAULT_THRESHOLD = 0.8;
const DEFAULT_LABEL = 'Budget';

function readNumber(key: string): number | null {
  try {
    const raw = localStorage.getItem(key);
    if (raw == null) return null;
    const n = Number(raw);
    if (!Number.isFinite(n) || n < 0) return null;
    return n;
  } catch {
    return null;
  }
}

function readString(key: string, fallback: string): string {
  try {
    const raw = localStorage.getItem(key);
    if (raw == null || raw.trim() === '') return fallback;
    return raw;
  } catch {
    return fallback;
  }
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

export interface BudgetSettings {
  budgetCents: number | null;
  threshold: number;
  label: string;
  setBudgetCents: (cents: number | null) => void;
  setThreshold: (threshold: number) => void;
  setLabel: (label: string) => void;
}

export function useBudgetSettings(): BudgetSettings {
  const [budgetCents, setBudgetCentsState] = useState<number | null>(() =>
    readNumber(CENTS_KEY),
  );
  const [threshold, setThresholdState] = useState<number>(() => {
    const t = readNumber(THRESHOLD_KEY);
    return t == null ? DEFAULT_THRESHOLD : clamp01(t);
  });
  const [label, setLabelState] = useState<string>(() => readString(LABEL_KEY, DEFAULT_LABEL));

  useEffect(() => {
    function onStorage(e: StorageEvent) {
      if (e.key === CENTS_KEY) setBudgetCentsState(readNumber(CENTS_KEY));
      if (e.key === THRESHOLD_KEY) {
        const t = readNumber(THRESHOLD_KEY);
        setThresholdState(t == null ? DEFAULT_THRESHOLD : clamp01(t));
      }
      if (e.key === LABEL_KEY) setLabelState(readString(LABEL_KEY, DEFAULT_LABEL));
    }
    window.addEventListener('storage', onStorage);
    return () => window.removeEventListener('storage', onStorage);
  }, []);

  const setBudgetCents = useCallback((cents: number | null) => {
    try {
      if (cents == null || cents <= 0) {
        // Clearing the cap also clears threshold + label (acceptance criteria).
        localStorage.removeItem(CENTS_KEY);
        localStorage.removeItem(THRESHOLD_KEY);
        localStorage.removeItem(LABEL_KEY);
        setBudgetCentsState(null);
        setThresholdState(DEFAULT_THRESHOLD);
        setLabelState(DEFAULT_LABEL);
      } else {
        localStorage.setItem(CENTS_KEY, String(cents));
        setBudgetCentsState(cents);
      }
    } catch {
      // ignore storage errors
    }
  }, []);

  const setThreshold = useCallback((t: number) => {
    const clamped = clamp01(t);
    setThresholdState(clamped);
    try {
      localStorage.setItem(THRESHOLD_KEY, String(clamped));
    } catch {
      // ignore
    }
  }, []);

  const setLabel = useCallback((l: string) => {
    setLabelState(l);
    try {
      localStorage.setItem(LABEL_KEY, l);
    } catch {
      // ignore
    }
  }, []);

  return { budgetCents, threshold, label, setBudgetCents, setThreshold, setLabel };
}
