// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_m2-flows-workbench.md.
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  cancelRun,
  createRun,
  deleteRun,
  getBinding,
  getFlowBySlug,
  getFlowVersion,
  getRun,
  listBindings,
  listFlows,
  listRuns,
  restartFrom,
  retryNodeState,
  retryRun,
  tickRun,
} from '@/api/taskr';
import type { FlowSummary, FlowVersion, Run } from '@/types/taskr';

export const queryKeys = {
  runs: ['runs'] as const,
  run: (runId: string) => ['runs', runId] as const,
  flows: ['flows'] as const,
  flowBySlug: (slug: string) => ['flows', slug] as const,
  flowVersion: (flowVersionId: string) => ['flow_versions', flowVersionId] as const,
  bindings: ['bindings'] as const,
  binding: (bindingId: string) => ['bindings', bindingId] as const,
};

export function useRunList() {
  return useQuery({
    queryKey: queryKeys.runs,
    queryFn: listRuns,
    refetchInterval: 5_000,
  });
}

export function useRunsForFlow(flowId: string | undefined) {
  const { data, isLoading } = useRunList();
  if (!flowId || isLoading || !data) return [];
  return data.filter((run) => run.flow_id === flowId);
}

export function useFlows() {
  return useQuery({
    queryKey: queryKeys.flows,
    queryFn: listFlows,
  });
}

export function useFlowBySlug(slug: string | undefined) {
  return useQuery<FlowSummary>({
    queryKey: queryKeys.flowBySlug(slug ?? 'missing'),
    queryFn: () => getFlowBySlug(slug ?? ''),
    enabled: Boolean(slug),
  });
}

export function useBindings() {
  return useQuery({ queryKey: queryKeys.bindings, queryFn: listBindings });
}

export function useBinding(bindingId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.binding(bindingId ?? 'missing'),
    queryFn: () => getBinding(bindingId ?? ''),
    enabled: Boolean(bindingId),
  });
}

export function isTerminalRun(run?: Pick<Run, 'status'> | null): boolean {
  return !!run && ['completed', 'failed', 'cancelled'].includes(run.status);
}

export function useRun(runId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.run(runId ?? 'missing'),
    queryFn: () => getRun(runId ?? ''),
    enabled: Boolean(runId),
    refetchInterval: (query) => {
      const data = query.state.data as Run | undefined;
      return isTerminalRun(data) ? false : 2_000;
    },
  });
}

export function useFlowVersion(flowVersionId: string | undefined) {
  return useQuery<FlowVersion>({
    queryKey: queryKeys.flowVersion(flowVersionId ?? 'missing'),
    queryFn: () => getFlowVersion(flowVersionId ?? ''),
    enabled: Boolean(flowVersionId),
  });
}

export function useCreateRun() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: createRun,
    onSuccess: (run) => {
      queryClient.setQueryData(queryKeys.run(run.id), run);
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}

export function useTickRun() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: tickRun,
    onSuccess: (run) => {
      queryClient.setQueryData(queryKeys.run(run.id), run);
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}

export function useCancelRun() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: cancelRun,
    onSuccess: (_result, runId) => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.run(runId) });
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}

export function useRetryRun() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: retryRun,
    onSuccess: (run) => {
      queryClient.setQueryData(queryKeys.run(run.id), run);
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}

export function useRestartFrom() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ runId, nodeId }: { runId: string; nodeId: string }) => restartFrom(runId, nodeId),
    onSuccess: (run) => {
      queryClient.setQueryData(queryKeys.run(run.id), run);
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}

export function useRetryNodeState(runId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (nodeStateId: string) => retryNodeState(runId, nodeStateId),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.run(runId) });
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}

export function useDeleteRun() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: deleteRun,
    onSuccess: (_result, runId) => {
      queryClient.removeQueries({ queryKey: queryKeys.run(runId) });
      void queryClient.invalidateQueries({ queryKey: queryKeys.runs });
    },
  });
}
