# FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at .hermes/plans/2026-06-29_120000-taskr-functional-fixes.md.
"""Integration tests for the real HTTP API integration.

These tests spin up a local HTTP server thread so the suite exercises real
HTTP requests without depending on external network services.
"""

from __future__ import annotations

import json
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any, Generator

import httpx
import pytest

from app.logic.integrations.api import ApiIntegration, resolve_url_template
from app.logic.integrations.fake import IntegrationResult


class _PingHandler(BaseHTTPRequestHandler):
    """Minimal handler for response, auth, and poll-mode API tests."""

    last_authorization: str | None = None

    def do_GET(self) -> None:  # noqa: N802
        type(self).last_authorization = self.headers.get("Authorization")
        if self.path == "/ok":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"message": "pong"}).encode())
        elif self.path == "/fail":
            self.send_response(500)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"internal server error")
        elif self.path == "/rate-limit":
            self.send_response(429)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"too many requests")
        elif self.path == "/status/job-running":
            self._send_json({"state": "processing"})
        elif self.path == "/status/job-123":
            self._send_json({"state": "COMPLETED", "result": {"summary": "done"}})
        elif self.path == "/status/job-failed":
            self._send_json({"state": "failed"})
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self) -> None:  # noqa: N802
        type(self).last_authorization = self.headers.get("Authorization")
        if self.path == "/start":
            self._send_json({"job": {"id": "job-123"}})
        else:
            self.send_response(404)
            self.end_headers()

    def _send_json(self, payload: dict[str, Any]) -> None:
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(payload).encode())

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002
        pass


@pytest.fixture
def api_integration() -> ApiIntegration:
    """Return an API integration with a short timeout for tests.

    Tests use a localhost server, so private addresses are allowed here.
    """
    return ApiIntegration(timeout=2.0, allow_private=True)


@pytest.fixture
def local_server() -> Generator[str, None, None]:
    """Yield the base URL of a local HTTP server that handles test routes."""
    _PingHandler.last_authorization = None
    server = HTTPServer(("127.0.0.1", 0), _PingHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    address = server.server_address
    yield f"http://{address[0]}:{address[1]}"
    server.shutdown()
    server.server_close()


def test_resolve_url_template_curly() -> None:
    """``resolve_url_template`` substitutes curly-braced placeholders."""
    template = "https://api.example.com/v1/items/{id}"
    assert resolve_url_template(template, {"id": "abc-123"}) == "https://api.example.com/v1/items/abc-123"


def test_resolve_url_template_dollar() -> None:
    """``resolve_url_template`` substitutes dollar-prefixed placeholders."""
    template = "https://api.example.com/v1/items/$id"
    assert resolve_url_template(template, {"id": "abc-123"}) == "https://api.example.com/v1/items/abc-123"


def test_resolve_url_template_missing_key_left_intact() -> None:
    """Unknown placeholders are left in the template so callers can re-resolve."""
    template = "https://api.example.com/v1/items/{id}/others/{other}"
    assert resolve_url_template(template, {"id": "abc"}) == "https://api.example.com/v1/items/abc/others/{other}"


def test_api_ping_success(api_integration: ApiIntegration, local_server: str) -> None:
    """A real GET to a 200 endpoint returns a completed result."""
    binding = {"method": "GET", "url_template": f"{local_server}/ok", "headers": {}}
    result = api_integration.start(binding, {})

    assert isinstance(result, IntegrationResult)
    assert result.status == "completed"
    assert result.output == {
        "status": "ok",
        "status_code": 200,
        "body": '{"message": "pong"}',
        "json": {"message": "pong"},
    }
    assert result.native_state == {"status_code": 200, "body": '{"message": "pong"}'}


def test_api_ping_failure(api_integration: ApiIntegration, local_server: str) -> None:
    """A real GET to a 500 endpoint returns a failed result."""
    binding = {"method": "GET", "url_template": f"{local_server}/fail", "headers": {}}
    result = api_integration.start(binding, {})

    assert isinstance(result, IntegrationResult)
    assert result.status == "failed"
    assert result.error_code == "http_error"
    assert "500" in (result.error_message or "")
    assert result.error_category == "http_server"
    assert result.retryable is False
    assert result.native_state is not None
    assert result.native_state.get("status_code") == 500


def test_api_rate_limit_failure_is_retryable(api_integration: ApiIntegration, local_server: str) -> None:
    """HTTP 429 failures are classified as retryable server-side failures."""
    binding = {"method": "GET", "url_template": f"{local_server}/rate-limit", "headers": {}}
    result = api_integration.start(binding, {})

    assert result.status == "failed"
    assert result.error_category == "http_server"
    assert result.retryable is True
    assert result.native_state is not None
    assert result.native_state.get("status_code") == 429


def test_api_not_found_failure_is_not_retryable(api_integration: ApiIntegration, local_server: str) -> None:
    """HTTP 404 failures are classified as non-retryable client errors."""
    binding = {"method": "GET", "url_template": f"{local_server}/missing", "headers": {}}
    result = api_integration.start(binding, {})

    assert result.status == "failed"
    assert result.error_category == "http_client"
    assert result.retryable is False
    assert result.native_state is not None
    assert result.native_state.get("status_code") == 404


def test_api_timeout_failure_is_retryable(api_integration: ApiIntegration, monkeypatch: pytest.MonkeyPatch) -> None:
    """httpx timeout exceptions are classified as retryable timeout failures."""

    def raise_timeout(*args: Any, **kwargs: Any) -> None:
        raise httpx.ConnectTimeout("timed out")

    monkeypatch.setattr(httpx, "request", raise_timeout)

    binding = {"method": "GET", "url_template": "https://example.test/timeout", "headers": {}}
    result = api_integration.start(binding, {})

    assert result.status == "failed"
    assert result.error_code == "timeout"
    assert result.error_category == "timeout"
    assert result.retryable is True


def test_api_auth_from_env(api_integration: ApiIntegration, local_server: str, monkeypatch: pytest.MonkeyPatch) -> None:
    """auth_ref resolves to a bearer token from TASKR_AUTH_<REF>."""
    monkeypatch.setenv("TASKR_AUTH_TEST_API", "[REDACTED]")
    binding = {"method": "GET", "url_template": f"{local_server}/ok", "auth_ref": "test-api"}

    result = api_integration.start(binding, {})

    assert result.status == "completed"
    assert _PingHandler.last_authorization == "Bearer [REDACTED]"


def test_api_explicit_authorization_header_wins(
    api_integration: ApiIntegration,
    local_server: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A binding-supplied Authorization header is not overwritten by auth_ref."""
    monkeypatch.setenv("TASKR_AUTH_TEST_API", "[REDACTED]")
    binding = {
        "method": "GET",
        "url_template": f"{local_server}/ok",
        "auth_ref": "test-api",
        "headers": {"Authorization": "Bearer explicit-[REDACTED]"},
    }

    result = api_integration.start(binding, {})

    assert result.status == "completed"
    assert _PingHandler.last_authorization == "Bearer explicit-[REDACTED]"


def test_api_missing_auth_ref_or_env_omits_authorization(
    api_integration: ApiIntegration,
    local_server: str,
) -> None:
    """Missing auth material leaves Authorization absent."""
    binding = {"method": "GET", "url_template": f"{local_server}/ok", "auth_ref": "missing-api"}

    result = api_integration.start(binding, {})

    assert result.status == "completed"
    assert _PingHandler.last_authorization is None


def test_api_poll_start_extracts_external_ref(api_integration: ApiIntegration, local_server: str) -> None:
    """Poll mode start returns running with the extracted external ref."""
    binding = {
        "method": "POST",
        "url_template": f"{local_server}/start",
        "completion_mode": "poll",
        "external_ref_path": "job.id",
    }

    result = api_integration.start(binding, {"payload": "ignored"})

    assert result.status == "running"
    assert result.external_ref == "job-123"
    assert result.native_state == {"status_code": 200, "body": {"job": {"id": "job-123"}}}


def test_api_poll_inspect_running(api_integration: ApiIntegration, local_server: str) -> None:
    """Intermediate status values keep the integration running."""
    binding = {
        "completion_mode": "poll",
        "status_url_template": f"{local_server}/status/{{external_ref}}",
        "status_path": "state",
        "success_values": ["done"],
        "failure_values": ["failed"],
    }

    result = api_integration.inspect("job-running", binding)

    assert result.status == "running"
    assert result.external_ref == "job-running"


def test_api_poll_inspect_completed_with_result_path(api_integration: ApiIntegration, local_server: str) -> None:
    """Success status completes and extracts output through result_path."""
    binding = {
        "completion_mode": "poll",
        "status_url_template": f"{local_server}/status/{{ref}}",
        "status_path": "state",
        "success_values": ["completed"],
        "failure_values": ["failed"],
        "result_path": "result.summary",
    }

    result = api_integration.inspect("job-123", binding)

    assert result.status == "completed"
    assert result.external_ref == "job-123"
    assert result.output == "done"


def test_api_poll_inspect_failed(api_integration: ApiIntegration, local_server: str) -> None:
    """Failure status values return failed with an external_failure code."""
    binding = {
        "completion_mode": "poll",
        "status_url_template": f"{local_server}/status/{{external_ref}}",
        "status_path": "state",
        "success_values": ["completed"],
        "failure_values": ["failed"],
    }

    result = api_integration.inspect("job-failed", binding)

    assert result.status == "failed"
    assert result.external_ref == "job-failed"
    assert result.error_code == "external_failure"
    assert result.error_category == "external_failure"
    assert result.retryable is False


def test_api_inspect_response_mode_returns_failure(api_integration: ApiIntegration) -> None:
    """Inspect is supported only for poll-mode API bindings."""
    result = api_integration.inspect("ref-123", {})

    assert result.status == "failed"
    assert result.error_code == "inspect_not_supported"
    assert result.error_category == "unknown"
    assert result.retryable is False


def test_api_ssrf_blocks_private_url() -> None:
    """Private/loopback URLs are rejected unless allow_private is set."""
    integration = ApiIntegration(timeout=2.0)
    binding = {"method": "GET", "url_template": "http://127.0.0.1:9999/secrets", "headers": {}}

    result = integration.start(binding, {})

    assert result.status == "failed"
    assert result.error_code == "invalid_url"
    assert result.error_category == "configuration"
    assert result.retryable is False


def test_api_ssrf_blocks_non_http_scheme() -> None:
    """Non-HTTP(S) schemes are rejected."""
    integration = ApiIntegration(timeout=2.0)
    binding = {"method": "GET", "url_template": "file:///etc/passwd", "headers": {}}

    result = integration.start(binding, {})

    assert result.status == "failed"
    assert result.error_code == "invalid_url"
