// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_taskr-frontend-integration.md.
import type { ApiError, ApiErrorShape } from '@/types/taskr';

const rawBase = import.meta.env.VITE_API_BASE ?? '';
const API_BASE = rawBase.endsWith('/') ? rawBase.slice(0, -1) : rawBase;

function buildUrl(path: string): string {
  if (!API_BASE) {
    return path;
  }
  return `${API_BASE}${path}`;
}

export async function apiRequest<T>(path: string, init?: RequestInit): Promise<T> {
  const headers = new Headers(init?.headers ?? {});
  if (!headers.has('Accept')) {
    headers.set('Accept', 'application/json');
  }
  if (init?.body && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }

  const response = await fetch(buildUrl(path), {
    ...init,
    headers,
  });

  if (!response.ok) {
    let detail = `Request failed with status ${response.status}`;
    let entityId: string | undefined;

    try {
      const payload = (await response.json()) as ApiErrorShape;
      detail = payload.detail ?? detail;
      entityId = payload.entity_id;
    } catch {
      const body = await response.text();
      if (body) {
        detail = body;
      }
    }

    const error = new Error(detail) as ApiError;
    error.status = response.status;
    error.entityId = entityId;
    throw error;
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}
