// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_taskr-frontend-integration.md.
import type { ApiError, ApiErrorShape } from '@/types/taskr';

const rawBase = import.meta.env.VITE_API_BASE ?? '';
const API_BASE = rawBase.endsWith('/') ? rawBase.slice(0, -1) : rawBase;

function buildUrl(path: string): string {
  if (!API_BASE) {
    return path;
  }
  return `${API_BASE}${path}`;
}

export async function apiRequest<T>(path: string, init?: RequestInit): Promise<T> {
  const headers = new Headers(init?.headers ?? {});
  if (!headers.has('Accept')) {
    headers.set('Accept', 'application/json');
  }
  if (init?.body && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }

  const response = await fetch(buildUrl(path), {
    ...init,
    headers,
  });

  if (!response.ok) {
    let detail = `Request failed with status ${response.status}`;
    let entityId: string | undefined;
    const body = await response.text();
    const bodyPreview = `${body.slice(0, 200)}${body.length > 200 ? '…' : ''}`;

    if (body.trim().toLowerCase().startsWith('<!doctype') || body.trim().startsWith('<')) {
      const error = new Error(
        `Backend returned HTML for ${path}. Is the backend running and reachable? (status ${response.status})`
      ) as ApiError;
      error.status = response.status;
      error.entityId = entityId;
      throw error;
    }

    try {
      const payload = JSON.parse(body) as ApiErrorShape;
      detail = payload.detail ?? detail;
      entityId = payload.entity_id;
    } catch {
      if (body) {
        detail = `${detail}: ${bodyPreview}`;
      }
    }

    const error = new Error(detail) as ApiError;
    error.status = response.status;
    error.entityId = entityId;
    throw error;
  }

  if (response.status === 204) {
    return undefined as T;
  }

  const body = await response.text();
  try {
    return JSON.parse(body) as T;
  } catch {
    if (body.trim().toLowerCase().startsWith('<!doctype') || body.trim().startsWith('<')) {
      const error = new Error(
        `Backend returned HTML for ${path}. Is the backend running and reachable? (status ${response.status})`
      ) as ApiError;
      error.status = response.status;
      throw error;
    }
    const error = new Error(`Invalid JSON response from ${path}: ${body.slice(0, 200)}${body.length > 200 ? '…' : ''}`) as ApiError;
    error.status = response.status;
    throw error;
  }
}
