// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_m2-flows-workbench.md.
import { apiRequest } from '@/api/client';
import type {
  Binding,
  CreateRunRequest,
  FlowSummary,
  FlowVersion,
  RestartFromResponse,
  RetryNodeResponse,
  Run,
  RunActionResponse,
  RunListItem,
} from '@/types/taskr';

export function listRuns(): Promise<RunListItem[]> {
  return apiRequest<RunListItem[]>('/runs');
}

export function createRun(payload: CreateRunRequest): Promise<Run> {
  return apiRequest<Run>('/runs', {
    method: 'POST',
    body: JSON.stringify(payload),
  });
}

export function getRun(runId: string): Promise<Run> {
  return apiRequest<Run>(`/runs/${runId}`);
}

export function tickRun(runId: string): Promise<Run> {
  return apiRequest<Run>(`/runs/${runId}/tick`, {
    method: 'POST',
  });
}

export function cancelRun(runId: string): Promise<RunActionResponse> {
  return apiRequest<RunActionResponse>(`/runs/${runId}/cancel`, {
    method: 'POST',
  });
}

export function retryRun(runId: string): Promise<Run> {
  return apiRequest<Run>(`/runs/${runId}/retry`, {
    method: 'POST',
  });
}

export function restartFrom(runId: string, nodeId: string): Promise<RestartFromResponse> {
  return apiRequest<RestartFromResponse>(`/runs/${runId}/restart_from`, {
    method: 'POST',
    body: JSON.stringify({ node_id: nodeId }),
  });
}

export function retryNodeState(runId: string, nodeStateId: string): Promise<RetryNodeResponse> {
  return apiRequest<RetryNodeResponse>(`/runs/${runId}/node-states/${nodeStateId}/retry`, {
    method: 'POST',
  });
}

export function deleteRun(runId: string): Promise<RunActionResponse> {
  return apiRequest<RunActionResponse>(`/runs/${runId}`, {
    method: 'DELETE',
  });
}

export function listFlows(): Promise<FlowSummary[]> {
  return apiRequest<FlowSummary[]>('/flows');
}

export function getFlowBySlug(slug: string): Promise<FlowSummary> {
  return apiRequest<FlowSummary>(`/flows/${slug}`);
}

export function getFlowVersion(flowVersionId: string): Promise<FlowVersion> {
  return apiRequest<FlowVersion>(`/flow_versions/${flowVersionId}`);
}

export function listBindings(): Promise<Binding[]> {
  return apiRequest<Binding[]>('/bindings');
}

export function getBinding(bindingId: string): Promise<Binding> {
  return apiRequest<Binding>(`/bindings/${bindingId}`);
}
