// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /agent/projects/taskr/Frontend/.hermes/plans/2026-06-30_frontend-fixes-plan.md.
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue =
  | JsonPrimitive
  | JsonValue[]
  | {
      [key: string]: JsonValue;
    };

export type RunStatus =
  | 'pending'
  | 'running'
  | 'paused'
  | 'completed'
  | 'failed'
  | 'cancelled';

export type NodeStateStatus =
  | 'pending'
  | 'ready'
  | 'dispatching'
  | 'running'
  | 'completed'
  | 'failed'
  | 'cancelled';

export type FlowNodeKind = 'api' | 'hermes' | 'foreach';
export type FlowVersionStatus = 'draft' | 'active' | 'archived';
export type BindingKind = 'api' | 'hermes';

export type InspectorTab = 'overview' | 'input' | 'output' | 'native' | 'loop';

export interface ApiErrorShape {
  detail?: string;
  entity_id?: string;
}

export interface ApiError extends Error {
  status: number;
  entityId?: string;
}

export interface NodeState {
  id: string;
  run_id: string;
  node_id: string;
  node_title: string | null;
  node_kind: FlowNodeKind | null;
  loop_iteration_id: string | null;
  status: NodeStateStatus;
  binding_id: string | null;
  binding_snapshot: JsonValue | null;
  external_ref: string | null;
  input: JsonValue | null;
  raw_output: JsonValue | null;
  output: JsonValue | null;
  cost_cents: number;
  error_code: string | null;
  error_message: string | null;
  attempt: number;
  created_at: string | null;
  started_at: string | null;
  finished_at: string | null;
  updated_at: string | null;
}

export interface Run {
  id: string;
  status: RunStatus;
  flow_id: string;
  flow_version_id: string;
  context: JsonValue | null;
  cost_cents: number;
  total_cost_cents: number;
  failure_summary: string | null;
  created_at: string | null;
  started_at: string | null;
  finished_at: string | null;
  node_states: NodeState[];
}

export type RunDetail = Run;

export interface RunListItem {
  id: string;
  status: RunStatus;
  flow_id: string;
  flow_version_id: string;
  total_cost_cents: number;
  created_at: string | null;
  started_at: string | null;
  finished_at: string | null;
}

export interface RunActionResponse {
  status: string;
  run_id: string | null;
}

export interface RestartFromResponse extends Run {
  source_run_id: string;
}

export interface RetryNodeResponse {
  status: string;
  node_state_id: string;
  run_id: string;
}

export interface CreateRunRequest {
  flow_slug?: string;
  flow_version_id?: string;
  context?: Record<string, JsonValue>;
}

export interface FlowSummary {
  id: string;
  title: string;
  slug: string;
  description: string;
  created_at: string | null;
  updated_at: string | null;
  active_flow_version_id?: string | null;
  active_flow_version_status?: 'draft' | 'active' | 'archived' | null;
}

export interface FlowNode {
  id: string;
  kind: FlowNodeKind;
  ord: number;
  title: string;
  parent_node_id: string | null;
  binding_id: string | null;
  input_mapping: JsonValue | null;
  output_mapping: JsonValue | null;
  items_path: string | null;
  item_key_path: string | null;
  failure_policy: 'stop' | 'continue' | null;
  policy_refs: string[] | null;
  children: FlowNode[];
}

export interface FlowVersion {
  id: string;
  flow_id: string;
  version: number;
  status: 'draft' | 'active' | 'archived';
  nodes: FlowNode[];
}

export type FlowVersionDetail = FlowVersion;

export interface ForeachIterationView {
  iterationId: string;
  status: NodeStateStatus;
  childStates: NodeState[];
}

export interface ForeachRuntimeView {
  nodeId: string;
  childNodeIds: string[];
  iterations: ForeachIterationView[];
}

export interface ApiBindingConfig {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  url_template: string;
  auth_ref: string | null;
  headers: Record<string, string>;
  request_mode: 'json' | 'query' | 'none';
  completion_mode: 'response' | 'poll';
  external_ref_path: string | null;
  status_method: 'GET' | 'POST';
  status_url_template: string | null;
  status_path: string | null;
  success_values: string[];
  failure_values: string[];
  result_path: string | null;
}

export interface HermesBindingConfig {
  board: string;
  profile: string | null;
  task_title_template: string;
  task_body_template: string;
  skills: string[];
  tenant_template: string | null;
  workspace_template: string | null;
  goal_mode: boolean;
}

export interface BindingBase {
  id: string;
  kind: BindingKind;
  display_title: string;
  is_enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface ApiBinding extends BindingBase {
  kind: 'api';
  config: ApiBindingConfig;
}

export interface HermesBinding extends BindingBase {
  kind: 'hermes';
  config: HermesBindingConfig;
}

export type Binding = ApiBinding | HermesBinding;
