// FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at /tmp/taskr-budget-frontend-plan.md.
import { useMemo, useState } from 'react';
import { useBudgetSettings } from '@/hooks/use-budget-settings';
import { useRunList } from '@/hooks/use-taskr';
import { formatCurrencyCents } from '@/lib/formatters';

export function BudgetSettingsPage() {
  const { budgetCents, threshold, label, setBudgetCents, setThreshold, setLabel } =
    useBudgetSettings();
  const runList = useRunList();

  const totalSpendCents = useMemo(
    () => (runList.data ?? []).reduce((sum, run) => sum + (run.total_cost_cents ?? 0), 0),
    [runList.data],
  );

  // Local input state so user can type before saving
  const [capDollars, setCapDollars] = useState<string>(
    budgetCents != null ? (budgetCents / 100).toFixed(2) : '',
  );
  const [thresholdPercent, setThresholdPercent] = useState<string>(
    `${Math.round(threshold * 100)}`,
  );
  const [labelInput, setLabelInput] = useState<string>(label);
  const [saved, setSaved] = useState(false);

  function handleSave() {
    const parsedDollars = Number.parseFloat(capDollars);
    const parsedCents = Number.isFinite(parsedDollars) ? Math.round(parsedDollars * 100) : 0;
    if (!Number.isFinite(parsedDollars) || parsedDollars <= 0) {
      // Clearing the cap also clears label and threshold.
      setBudgetCents(null);
      setCapDollars('');
      setThresholdPercent(`${Math.round(0.8 * 100)}`);
      setLabelInput('Monthly budget');
      setSaved(true);
      return;
    }
    setBudgetCents(parsedCents);
    const parsedThreshold = Number.parseFloat(thresholdPercent) / 100;
    setThreshold(Number.isFinite(parsedThreshold) ? parsedThreshold : 0.8);
    setLabel(labelInput);
    setSaved(true);
  }

  function handleClear() {
    setBudgetCents(null);
    setCapDollars('');
    setThresholdPercent(`${Math.round(0.8 * 100)}`);
    setLabelInput('Monthly budget');
    setSaved(false);
  }

  // Live preview values
  const previewCents =
    Number.isFinite(Number.parseFloat(capDollars)) && Number.parseFloat(capDollars) > 0
      ? Math.round(Number.parseFloat(capDollars) * 100)
      : null;
  const effectiveCap = previewCents ?? budgetCents;
  const pct =
    effectiveCap != null && effectiveCap > 0
      ? Math.min(100, (totalSpendCents / effectiveCap) * 100)
      : 0;
  const remaining = effectiveCap != null ? Math.max(0, effectiveCap - totalSpendCents) : null;
  const exhausted = remaining != null && remaining <= 0;
  const nearThreshold = !exhausted && effectiveCap != null && pct >= threshold * 100;

  const barColor = exhausted
    ? 'bg-rose-500'
    : nearThreshold
      ? 'bg-amber-400'
      : 'bg-accent';

  return (
    <div className="mx-auto max-w-2xl px-6 py-10">
      <p className="text-xs font-mono uppercase tracking-[0.2em] text-muted-foreground">Budget</p>
      <h1 className="mt-1 text-4xl font-bold uppercase tracking-[0.1em] text-accent">
        Budget settings
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Set a monthly cap, alert threshold, and label. Values persist in this browser only.
      </p>

      {/* Live progress bar */}
      <div className="mt-8 border border-border bg-bg-2 p-5">
        <div className="flex items-baseline justify-between">
          <span className="text-xs font-mono uppercase tracking-[0.2em] text-muted-foreground">
            Current spend
          </span>
          <span className="font-mono text-sm text-foreground/90">
            {formatCurrencyCents(totalSpendCents)}
            {effectiveCap != null ? ` / ${formatCurrencyCents(effectiveCap)}` : ''}
          </span>
        </div>
        <div className="mt-3 h-2 w-full bg-black/40">
          <div
            className={`h-full ${barColor} transition-[width] duration-300`}
            style={{ width: `${pct}%` }}
          />
        </div>
        <div className="mt-2 flex items-baseline justify-between font-mono text-xs">
          <span className={exhausted ? 'text-rose-400' : nearThreshold ? 'text-amber-300' : 'text-muted-foreground'}>
            {exhausted ? 'Exhausted' : nearThreshold ? 'Near threshold' : 'Under budget'}
          </span>
          {remaining != null && (
            <span className={exhausted ? 'text-rose-400' : 'text-muted-foreground'}>
              {formatCurrencyCents(remaining)} remaining
            </span>
          )}
        </div>
      </div>

      {/* Inputs */}
      <div className="mt-6 space-y-5">
        <div>
          <label
            htmlFor="budget-cap"
            className="block text-xs font-mono uppercase tracking-[0.2em] text-muted-foreground"
          >
            Monthly cap ($)
          </label>
          <input
            id="budget-cap"
            type="number"
            min="0"
            step="0.01"
            inputMode="decimal"
            value={capDollars}
            onChange={(e) => {
              setCapDollars(e.target.value);
              setSaved(false);
            }}
            placeholder="0.00"
            className="mt-1.5 w-full border border-border bg-bg-1 px-3 py-2 font-mono text-sm text-foreground outline-none focus:border-accent"
          />
        </div>

        <div>
          <label
            htmlFor="budget-threshold"
            className="block text-xs font-mono uppercase tracking-[0.2em] text-muted-foreground"
          >
            Alert threshold (%)
          </label>
          <input
            id="budget-threshold"
            type="number"
            min="0"
            max="100"
            step="1"
            inputMode="numeric"
            value={thresholdPercent}
            onChange={(e) => {
              setThresholdPercent(e.target.value);
              setSaved(false);
            }}
            placeholder="80"
            className="mt-1.5 w-full border border-border bg-bg-1 px-3 py-2 font-mono text-sm text-foreground outline-none focus:border-accent"
          />
        </div>

        <div>
          <label
            htmlFor="budget-label"
            className="block text-xs font-mono uppercase tracking-[0.2em] text-muted-foreground"
          >
            Label
          </label>
          <input
            id="budget-label"
            type="text"
            value={labelInput}
            onChange={(e) => {
              setLabelInput(e.target.value);
              setSaved(false);
            }}
            placeholder="Monthly budget"
            className="mt-1.5 w-full border border-border bg-bg-1 px-3 py-2 font-mono text-sm text-foreground outline-none focus:border-accent"
          />
        </div>

        <div className="flex gap-3 pt-2">
          <button
            type="button"
            onClick={handleSave}
            className="border border-accent bg-accent px-5 py-2 font-mono text-sm font-medium uppercase tracking-[0.1em] text-bg-1 transition-colors hover:bg-[var(--color-accent-hover)]"
          >
            Save
          </button>
          <button
            type="button"
            onClick={handleClear}
            className="border border-border bg-transparent px-5 py-2 font-mono text-sm font-medium uppercase tracking-[0.1em] text-foreground transition-colors hover:border-accent hover:text-accent"
          >
            Clear cap
          </button>
          {saved && (
            <span className="self-center font-mono text-xs text-accent">Saved</span>
          )}
        </div>
      </div>
    </div>
  );
}
