# FLOW-PRODUCED: generated by lean-adversarial-dev dispatch. Do not hand-edit without checking the plan at .hermes/plans/2026-06-29_120000-taskr-functional-fixes.md.

from __future__ import annotations

from typing import Any

from fastapi import APIRouter

from app.data.repository import TaskrRepository
from app.endpoint.builders import build_binding_response
from app.endpoint.deps import _get_repo
from app.endpoint.models_bindings import (
    ApiBindingConfig,
    ApiBindingCreateRequest,
    ApiBindingResponse,
    ApiBindingUpdateRequest,
    BindingCreateRequest,
    BindingResponse,
    BindingUpdateRequest,
    HermesBindingConfig,
    HermesBindingCreateRequest,
    HermesBindingResponse,
    HermesBindingUpdateRequest,
)
from app.errors.binding import BindingInUseError, BindingKindMismatchError, BindingNotFoundError

"""Integration binding CRUD endpoints.

A binding is a reusable connection configuration that tells a flow node how to
talk to an external system. Bindings are a discriminated union: `kind` is either
"api" or "hermes", and the kind-specific config is stored in a dedicated child
table. Endpoints here raise typed domain exceptions handled by the central
exception handler.
"""

router = APIRouter()


@router.get(
    "/bindings",
    response_model=list[BindingResponse],
    tags=["Bindings"],
    operation_id="bindings_list_bindings",
    summary="List bindings",
)
def list_bindings() -> list[dict[str, Any]]:
    """List all integration bindings.

    Returns:
        A list of binding records with nested kind-specific config.
    """
    repo = _get_repo()
    bindings = repo.load_all_bindings()
    return [build_binding_response(b) for b in bindings]


@router.post(
    "/bindings",
    response_model=BindingResponse,
    tags=["Bindings"],
    status_code=201,
    operation_id="bindings_create_binding",
    summary="Create a binding",
)
def create_binding(body: BindingCreateRequest) -> dict[str, Any]:
    """Create a new integration binding.

    Args:
        body: A discriminated union of API or Hermes binding create payloads.

    Returns:
        The newly created binding record with nested config.
    """
    repo = _get_repo()
    data = _flatten_create_request(body)
    binding = repo.create_binding(
        kind=data["kind"],
        display_title=data["display_title"],
        is_enabled=data["is_enabled"],
        config=data["config"],
    )
    return build_binding_response(binding)


@router.get(
    "/bindings/{binding_id}",
    response_model=BindingResponse,
    tags=["Bindings"],
    operation_id="bindings_get_binding",
    summary="Get a binding",
)
def get_binding(binding_id: str) -> dict[str, Any]:
    """Retrieve a single integration binding.

    Args:
        binding_id: The unique binding identifier.

    Returns:
        The binding record with nested config.

    Raises:
        BindingNotFoundError: 404 if the binding does not exist.
    """
    repo = _get_repo()
    binding = repo.load_binding(binding_id)
    if binding is None:
        raise BindingNotFoundError(f"Binding {binding_id} not found", entity_id=binding_id)
    return build_binding_response(binding)


@router.put(
    "/bindings/{binding_id}",
    response_model=BindingResponse,
    tags=["Bindings"],
    operation_id="bindings_update_binding",
    summary="Update a binding",
)
def update_binding(binding_id: str, body: BindingUpdateRequest) -> dict[str, Any]:
    """Update an integration binding.

    Args:
        binding_id: The unique binding identifier.
        body: A discriminated union of API or Hermes binding update payloads.

    Returns:
        The updated binding record with nested config.

    Raises:
        BindingNotFoundError: 404 if the binding does not exist.
        BindingKindMismatchError: 400 if the body kind does not match the stored kind.
    """
    repo = _get_repo()
    existing = repo.load_binding(binding_id)
    if existing is None:
        raise BindingNotFoundError(f"Binding {binding_id} not found", entity_id=binding_id)

    data = _flatten_update_request(body, existing_kind=existing["kind"], binding_id=binding_id)
    binding = repo.update_binding(
        binding_id,
        display_title=data.get("display_title"),
        is_enabled=data.get("is_enabled"),
        config=data.get("config"),
    )
    return build_binding_response(binding)


@router.delete(
    "/bindings/{binding_id}",
    tags=["Bindings"],
    operation_id="bindings_delete_binding",
    summary="Delete a binding",
)
def delete_binding(binding_id: str) -> dict[str, Any]:
    """Delete an integration binding.

    Args:
        binding_id: The unique binding identifier.

    Returns:
        A confirmation status.

    Raises:
        BindingNotFoundError: 404 if the binding does not exist.
        BindingInUseError: 409 if the binding is referenced by a flow node.
    """
    repo = _get_repo()
    existing = repo.load_binding(binding_id)
    if existing is None:
        raise BindingNotFoundError(f"Binding {binding_id} not found", entity_id=binding_id)
    if repo.binding_is_in_use(binding_id):
        raise BindingInUseError(f"Binding {binding_id} is in use", entity_id=binding_id)
    repo.delete_binding(binding_id)
    return {"status": "deleted", "binding_id": binding_id}


# ── Request flattening helpers ───────────────────────────────


def _flatten_create_request(body: BindingCreateRequest) -> dict[str, Any]:
    """Convert a discriminated create request into a flat dict for the repository."""
    data = body.model_dump()
    return {
        "kind": data["kind"],
        "display_title": data["display_title"],
        "is_enabled": data["is_enabled"],
        "config": data["config"],
    }


def _flatten_update_request(
    body: BindingUpdateRequest, *, existing_kind: str, binding_id: str
) -> dict[str, Any]:
    """Convert a discriminated update request into a flat dict, validating kind consistency."""
    data = body.model_dump(exclude_unset=True)
    body_kind = data["kind"]
    if body_kind != existing_kind:
        raise BindingKindMismatchError(
            f"Cannot change binding kind from {existing_kind} to {body_kind}",
            entity_id=binding_id,
        )
    return {
        "display_title": data.get("display_title"),
        "is_enabled": data.get("is_enabled"),
        "config": data.get("config"),
    }
